#!/bin/sh

CDIR=$(pwd)
APP=$(basename $CDIR)

function build_commands {
    if [ $# -lt 1 ]
    then
        echo "🚨 Specify which CSV file to build commands from."
    else
        python3 tools/build_data.py -f $1 | sed 's/\\\\/\\/g'
    fi
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n
}

"${@:-help}"
