#!/bin/sh

# CHECK TO MAKE SURE `//` ISN'T PRESENT IN DATA FILE

# Redirect output to stderr.
exec 1>&2

# Check all staged files
regex='\\\\'
if test $(git diff --cached | egrep $regex | wc -l) != 0
then
    echo "🚨 Whoops! You forgot to remove the `\\` from the data file..."
    exit 1
else 
    exit 0
fi